---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/docker/

my-docker:
  # socket: /var/run/docker.sock
  # host: host.docker.internal
  # host: 127.0.0.1
  host: dockerproxy
  port: 2375
