---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

title: Homepage for Home Server
background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
cardBlur: sm
theme: dark
language: en
showStats: true
useEqualHeights: true

layout:
  Media:
    style: row
    columns: 2
  Infrastructure:
    style: row
    columns: 3
  Links:
    style: row
    columns: 2

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
  finnhub: cs831dhr01qsceftitp0cs831dhr01qsceftitpg
