---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/service-widgets

- resources:
    cpu: true
    memory: true
    cputemp: true
    units: metric # only used by cpu temp
    uptime: true
    disk: /
    expanded: true

- search:
    provider: duckduckgo
    target: _blank
    showSearchSuggestions: true

- openmeteo:
    label: Belgrade # optional
    latitude: 50.52
    longitude: 13.41
    timezone: Europe/Belgrade # optional
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1

- stocks:
    provider: finnhub
    watchlist:
      - BTC
