services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - '127.0.0.1:2375:2375'
    restart: unless-stopped
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - ../configs/homepage:/app/config
      - ${DOCKER_SOCK}:/var/run/docker.sock:ro
    environment:
      PUID: $PUID
      PGID: $PGID
    env_file: "../.env"
    # ports:
    #   - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: curl --fail localhost:3000 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s
