services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    volumes:
      - ./homebridge:/homebridge
    env_file: "../.env"
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: curl --fail localhost:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
