services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - ${DOCKER_SOCK}:/var/run/docker.sock
    ports:
      - '9999:8080'
    restart: unless-stopped
    healthcheck:
      test: curl --fail localhost:8080 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s
    labels:
      - homepage.group=Infrastructure
      - homepage.name=Dozzle
      - homepage.icon=dozzle.png
      - homepage.href=http://${BASE_DOMAIN}:9999/
      - homepage.description=Docker logs
      - homepage.ping=http://${BASE_DOMAIN}:9999/
  noip:
    image: ghcr.io/noipcom/noip-duc:latest
    container_name: noip-duc
    env_file: "../.env"
    restart: unless-stopped
    labels:
      - homepage.group=Infrastructure
      - homepage.name=NoIP
      - homepage.icon=ddns-updater.png
      - homepage.description=DDNS Updater

  ssh_server:
    image: serversideup/docker-ssh
    container_name: ssh_server
    configs:
      - source: ssh_authorized_keys
        target: /authorized_keys
        mode: 600
    env_file: "../.env"
    ports:
      - '2223:2222'
    restart: unless-stopped
    labels:
      - homepage.group=Infrastructure
      - homepage.name=SshServer
      - homepage.icon=terminal.png
      - homepage.description=SSH Server
