services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - ${DOCKER_SOCK}:/var/run/docker.sock
      - ../configs/dozzle:/data
    ports:
      - '9999:8080'
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 300s
    labels:
      - homepage.group=Infrastructure
      - homepage.name=Dozzle
      - homepage.icon=dozzle.png
      - homepage.href=http://dozzle.${BASE_DOMAIN}/
      - homepage.description=Docker logs

  noip:
    image: ghcr.io/noipcom/noip-duc:latest
    container_name: noip-duc
    env_file: "../.env"
    restart: unless-stopped
    labels:
      - homepage.group=Infrastructure
      - homepage.name=NoIP
      - homepage.icon=ddns-updater.png
      - homepage.description=DDNS Updater

  ssh_server:
    image: serversideup/docker-ssh
    container_name: ssh_server
    configs:
      - source: ssh_authorized_keys
        target: /authorized_keys
        mode: 600
    env_file: "../.env"
    ports:
      - '2223:2222'
    restart: unless-stopped
    labels:
      - homepage.group=Infrastructure
      - homepage.name=SshServer
      - homepage.icon=terminal.png
      - homepage.description=SSH Server
