services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
    ports:
      - '3389:3389/tcp'
      - '3389:3389/udp'
      - '8006:8006'
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/kvm
    stop_grace_period: 2m
